version: "3.1"

services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    restart: always
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - "27017:27017"

  snake_front:
    build: ./front
    container_name: snake_front
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - snake_back

  snake_back:
    build: ./back
    restart: always
    depends_on:
      - mongodb
    container_name: snake_back
    environment:
      - MONGO=mongodb
    ports:
      - "8080:8080"
